service: quotebot

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1 # Overwrite the default region used. Default is us-east-1
  timeout: 100


functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: webhook
          method: GET
          cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
      - http:
          path: webhook
          method: POST
          cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
plugins:
  - serverless-offline
